version: '3.9'

services:
  app:
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile

    # Map port from container to host
    ports:
      - "3000:3000"

    # Load environment variables
    env_file: 
      - .env

    # Always restart unless manually stopped
    restart: unless-stopped
